spring:
  security:
    user:
      name: none
      password: none



oauth:
  custom:
    google-client-id: ${GOOGLE_CLIENT_ID}
    google-client-secret: ${GOOGLE_CLIENT_SECRET}
    naver-client-id: ${NAVER_CLIENT_ID}
    naver-client-secret: ${NAVER_CLIENT_SECRET}

